# Generated by Django 3.1.1 on 2020-10-08 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0002_auto_20201008_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now=True)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdfund.reward')),
            ],
        ),
    ]
