# Generated by Django 3.1.1 on 2020-10-08 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0003_perk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perk',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perks', to='crowdfund.reward'),
        ),
    ]
