# Generated by Django 3.1.1 on 2020-10-08 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0004_auto_20201008_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='description',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='short_description',
        ),
    ]
