# Generated by Django 3.1.1 on 2020-10-20 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0007_paystackinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaystackInfo',
        ),
    ]
