# Generated by Django 3.1.1 on 2020-10-21 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0008_delete_paystackinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyAskedQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='FrequentlyAskedQuestionDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdfund.frequentlyaskedquestion')),
            ],
        ),
    ]
