# Generated by Django 3.1.1 on 2020-10-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0011_gallery_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Galleries'},
        ),
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
