# Generated by Django 3.1.1 on 2020-12-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0013_order_paystack_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
