# Generated by Django 3.1.1 on 2020-12-30 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0017_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
    ]
